services:
  issuer-backend:
    image: ghcr.io/openwallet-foundation-labs/credhub/issuer-backend
    environment:
      - OIDC_AUTH_URL=$OIDC_AUTH_URL
      - OIDC_REALM=$OIDC_REALM
      - OIDC_CLIENT_ID=$OIDC_CLIENT_ID
      - VERIFIER_BASE_URL=$VERIFIER_BASE_URL
      - KM_FOLDER=$KM_FOLDER
      - ISSUER_BASE_URL=$ISSUER_BASE_URL
      - CREDENTIALS_FOLDER=$CREDENTIALS_FOLDER
      - DB_TYPE=sqlite
      - DB_NAME=data/db.sqlite
    volumes:
      - issuer:/home/node/app/data:rw
      - ./config/issuer-backend:/home/node/app/templates
    ports:
      - $BACKEND_PORT:3000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

  issuer-frontend:
    image: ghcr.io/openwallet-foundation-labs/credhub/issuer-frontend
    volumes:
      - ./config/issuer-frontend/config.json:/usr/share/nginx/html/assets/config.json
    ports:
      - $FRONTEND_PORT:80

volumes:
  issuer:
