name: Build and Push Docker images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
    contents: read
    packages: write

jobs:  
  build-and-test:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: init env files
        run: pnpm run init

      - name: Test
        run: pnpm test

  build-and-push:
    runs-on: ubuntu-latest
    # only run this when it's a push to main
    if: github.ref == 'refs/heads/main'
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: copy env file
        run: cp .env.example .env

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      - name: Cleanup
        if: always()
        run: docker logout
